### PR TITLE
Feat: New setid command and updated CAN IDs

### PR DESCRIPTION
**Pull request by ArnavG-it**
The `setid` command can be used to set SOTI's sender ID, allowing it to masquerade as any subsystem when sending messages:

soti_setid

As per #20:
- Updated the subsystem node IDs to match the ones in the [CANWrapper](https://github.com/UMSATS/tsat-utilities-kit/blob/e6e9c9386bd9c61bc6a9d05f250f76c9c4067730/Inc/tuk/can_wrapper/can_message.h#L19-L25).
- Replaced the SYSTEM_IDS dictionary with an enum called NodeID.

Let me know if I missed anything, and feel free to make style changes.

### CODE REVIEW

**Review by Koloss0 — APPROVED** [review]
Awesome job! Did you test it with SOTI?

**Comment by ArnavG-it** [comment]
> Awesome job! Did you test it with SOTI?

I tested the python CLI locally (the COM1 port was available), but not connected to any hardware.

**Comment by Koloss0** [comment]
> > Awesome job! Did you test it with SOTI?
> 
> I tested the python CLI locally (the COM1 port was available), but not connected to any hardware.

Makes sense given I just tested the SOTI board and it doesn't seem to be working.

**Comment by ArnavG-it** [comment]
> Makes sense given I just tested the SOTI board and it doesn't seem to be working.

You can roll back the merge if you'd like. Let me know if I can help fix it.

**Comment by Koloss0** [comment]
Oh no, I mean it's faulty wiring. It has to do with the USB connection, not this PR

**Comment by ArnavG-it** [comment]
> Oh no, I mean it's faulty wiring. It has to do with the USB connection, not this PR

Oh, I see.

**Pull request merged**
