### PR TITLE
Feat: Command ID Enum and Updates

### PR DESCRIPTION
**Pull request by ArnavG-it**
Updates to the latest command reference.

Simplifies all satellite command-related code by introducing the `CmdID` enum, which is used for parsing, querying, `COMM_INFO`, and the `list` help string. This reduces hardcoding and should be easier to update in the future.

Makes some small changes to hex conversions and fixes some syntax errors related to `NodeID`.

A bug remains where sending common commands crashes the program as the destination ID is set to `None`. As a future issue, the user could specify which subsystem is the recipient.

TODO:
- [ ] Test parsing code (I've tested with pseudo-messages but it may be worth testing properly.)

### CODE REVIEW

**Comment by ArnavG-it** [comment]
Drafting this for my own organization, but if I missed something in the TODOs please add it.

**Comment by ArnavG-it** [comment]
@Koloss0 No worries about the late response!

Like you mentioned, I'll leave the common command issue for the future. Also, I'm not sure if anything needs to be tested with the board, but it might be worth it for the new parsing code. One more thing before this is complete:

[QUERY_ATTRS](https://github.com/UMSATS/soti/blob/022272fa3a9f7d9721c3daae4830a167af3546f4/soti-cli/cli_utils/constants.py#L202) needs to be updated. If I'm understanding right, it provides a name to certain commands when they're being written to the file, and you can also use those names to search the message history. Could we just remove it and take advantage of `CmdID` for these names? This would allow every command to have this feature, and we could let the user search by either enum value or name since the `list` command provides now both of these.

**Comment by Koloss0** [comment]
Yeah, that's part of the query feature of SOTI. To be honest, I don't know exactly how it works. I'm not even sure what it would be used for. I'm tempted to just remove it altogether. You should ask Daigh since he's the one who wrote it.

**Comment by DaighB** [comment]
We could just remove the specific query functionality and take advantage of CmdID for these names. Initially, the query code was meant only for telemetry messages. The idea was to have a way to request all of the telemetry data of a certain type, and display it in the terminal. However, being able to accomplish that for any type of message, using the CmdID would be great. That would probably help simplify code, and the overall JSON structure. The changes to the code are looking great so far. Awesome work!

**Comment by ArnavG-it** [comment]
@Koloss0 Should be ready for review! Just keep in mind I've only tested the parsing code on its own (not as part of the full program), so no guarantees there.

**Review by Koloss0 — APPROVED** [review]

**Comment by ArnavG-it** [comment]
Thanks for the changes Logan!

**Pull request merged**
