### PR TITLE
add command parsers 40-4A and 50-52

### PR DESCRIPTION
**Pull request by ArnavG-it**

### CODE REVIEW

**Comment by GrahamDrive** [comment]
I looked it over, I finally have some  grasp on this code base. Before approving were we ever able to test the new commands with the SOTI board?

**Comment by ArnavG-it** [comment]
> I looked it over, I finally have some grasp on this code base. Before approving were we ever able to test the new commands with the SOTI board?

I don't believe so. 

@DaighB recommended finishing the threading-overhaul branch before merging this one.

**Comment by GrahamDrive** [comment]
Ok yeah that makes sense. Sounds like a plan.

**Review by DaighB — APPROVED** [review]
This looks great! Awesome work!

**Pull request merged**
